# Generated by Django 4.2.16 on 2024-10-27 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="Default Title", max_length=255)),
                ("description", models.TextField(default="Default description")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="thread", name="created_by",),
        migrations.RemoveField(model_name="thread", name="forum",),
        migrations.RemoveField(model_name="comment", name="created_by",),
        migrations.RemoveField(model_name="comment", name="thread",),
        migrations.RemoveField(model_name="comment", name="updated_at",),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(name="Forum",),
        migrations.DeleteModel(name="Thread",),
        migrations.AddField(
            model_name="comment",
            name="forum_entry",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="forum.forumentry",
            ),
        ),
    ]
