# Generated by Django 4.2.16 on 2024-10-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_forumentry_remove_thread_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forumentry",
            name="description",
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name="forumentry",
            name="title",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
