# Generated by Django 5.1 on 2024-10-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='harga',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='restaurant_name',
        ),
        migrations.AddField(
            model_name='product',
            name='kategori',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='lokasi',
            field=models.CharField(default='Uncategorized', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='nama',
            field=models.CharField(default='Uncategorized', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='nama_restoran',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
