# Generated by Django 5.1.1 on 2024-10-24 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_moodentry_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodentry',
            name='feelings',
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='mood_intensity',
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='time',
        ),
        migrations.AddField(
            model_name='moodentry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
