# Generated by Django 5.1.2 on 2024-10-25 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_product'),
    ]

    operations = [
    ]
