# Generated by Django 5.1.1 on 2024-10-24 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_moodentry_feelings_remove_moodentry_mood_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoodEntry',
        ),
    ]
