# Generated by Django 5.1.2 on 2024-10-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewentry',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
