# Generated by Django 5.1.2 on 2024-10-26 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_reviewentry_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewentry',
            name='rating',
        ),
    ]
